---
- name: instal cre
  hosts: all
  become: yes
  tasks:
    - name: add kernel modules to load list
      blockinfile:
        path: /etc/modules-load.d/k8s.conf
        block: |
          overlay
          br_netfilter
        create: yes


    - name: load additional kernel modules immediately
      command: 
          cmd: '{{ item }}'
      loop: 
        - modprobe overlay
        - modprobe br_netfilter    
        
    - name: sysctl params required by setup, params persist across reboots
      blockinfile:
        path: /etc/sysctl.d/k8s.conf
        block: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward                 = 1
        create: yes


    - name: Apply sysctl params without reboot
      command:
         cmd: sysctl --system
